version: '3'

services:
  api:
    image: node
    env_file:
      - ./.env
    ports:
      - ${APIPORT}:${APIPORT}
    working_dir: /app/
    volumes:
      - ./:/app/
    tty: true
    stdin_open: true